module.exports = [
    "My name is Sgt. Frank Drebin, Detective Lieutenant Police Squad.",
    "It's the same old story. Boy finds girl, boy loses girl, girl finds boy, boy forgets girl, boy remembers girl, girl dies in a tragic blimp accident over the Orange Bowl on New Year's Day.",
    "Just think... next time I shoot someone, I could be arrested.",
    "Well, when I see five weirdos, dressed in togas, stabbing a man in the middle of the park in full view of a hundred people, I shoot the bastards, that's my policy!",
    "Jane, since I've met you, I've noticed things that I never knew were there before... birds singing, dew glistening on a newly formed leaf, stoplights.",
    "Cops and women don't mix. It's like eating a spoonful of Drano. Sure, it'll clean you out, but it'll leave you hollow inside.",
    "Frank: Now, Jane, what can you tell us about the man you saw last night? Jane: He's Caucasian. Ed: Caucasian? Jane: Yeah, you know, a white guy. A moustache. About six-foot-three. Frank: Awfully big moustache.",
    "Oh, it's all right. I'm sure that we can handle this situation maturely, just like the responsible adults that we are. Isn't that right, Mr... Poopy Pants?",
    "Wilma, I promise you; whatever scum did this, not one man on this force will rest one minute until he's behind bars. Now, let's grab a bite to eat.",
    "Looks like the cows have come home to roost.",
    "It's a topsy-turvy world, and maybe the problems of two people don't amount to a hill of beans. But this is our hill. And these are our beans!",
    "Real nice party, Hapsburg. I see a lot of familiar face-lifts",
    "The gloves are off - I'm playing hardball, Ludwig. It's fourth and fifteen and you're looking at a full-court press.",
    "The truth hurts, doesn't it, Hapsburg? Oh sure, maybe not as much as landing on a bicycle with the seat missing, but it hurts!",
    "You take a chance getting up in the morning, crossing the street or sticking your face in a fan.",
    "Cheer up, Ed. This is not goodbye. It's just I won't ever see you again.",
    "I'm Lt. Frank Drebin, Police Squad! And don't ever let me catch you guys in America!",
    "Hey! Look at that. The missing evidence in the Kelner case. My God! He was innocent!",
    "I'm sorry! I can't hear ya! Don't fire the gun while you're talking!",
    "[shakes hands] Drebin. Frank Drebin. I believe I've used some of your restrooms.",
    "I want a world where I can eat a sea otter without getting sick!",
    "What if he’s not blindfolded?",
    "I realise that... now...",
    "The feeling is mutual.",
    "You-might-end-up-dead is my middle name",
    "Ed: Sarge you haven't shot anyone in 6 months. Frank: That's true. Funny how you miss the little things.",
    "Might be good to feel that cold, hard steel pressed against my thigh once again. The thrill of the chase... to be a man!",
    "I guess love is like the Ozone layer... you never miss it until it's gone",
    "...Ancient history, like the Democratic party.",
    "Eddy: Piece of cake Lieutenant. Frank: No thanks, I just ate.",
    "Yes, he's in the intensive care ward at Our Lady of the Worthless Miracle",
    "Ed: You wanna take a Dinghy? Frank: No, no, I took care of that at the press conference.",
    "We’re sorry to bother you at such a time like this, Mrs Twice. We would have come earlier, but your husband wasn’t dead then.",
    "It took me two weeks to find Stella’s apartment. She had neglected to give me her address.",
    "Well… it's very impressive, yes, but we need to ask you a few questions.",
    "Sorry, Buddy. No sax before a fight.",
    "When I got home I received a call from Mimi Du Jour, she wanted me to come to the club right away. Since I had no idea where the Club Rightaway was, I suggested to go to the Club Flamingo. She agreed.",
    "Ed and I drove around for hours for no particular reason. We came up empty.",
    "Doorman: Your coat, sir? Frank: Yes it is. And I have a receipt to prove it.",
    "[after his daughter is kidnapped] Warner Burton: What do I do?!? Frank: I believe you are in the textile industry.",
    "Dutch Gunderson: Who are you and how did you get in here? Frank: I’m the locksmith. And I’m the locksmith.",
    "No, you’re right, Ed. A parachute not opening – that’s a way to die. Getting caught in the gears of a combine, having your nuts bitten off by a Laplander… that’s the way I wanna go.",
    "He’s right, Wilma. But I wouldn’t wait until the last minute to fill out those organ donor cards.",
    "Unless he’s a drooling vegetable. But I think that’s only common sense.",
    "Hey! You call this slop? Real slop has got chunks of things in it! This is more like gruel! And this Château le Blanc '68 is supposed to be served slightly chilled! This is room temperature! What do you think we are? Animals?",
    "Protecting the Queen's safety is a task that is gladly accepted by Police Squad. No matter how silly the idea of having a queen might be to us, as Americans, we must be gracious and considerate hosts.",
    "This is Frank Drebin, Police Squad. Throw down your guns, and come on out with your hands up. Or come on out, then throw down your guns, whichever way you wanna do it. Just remember the two key elements here: one, guns to be thrown down; two, come on out!",
    "Jane: Can I interest you in a nightcap? Frank: No, thank you, I don't wear them.",
    "Ed: We heard about you and Jane. Frank: Jane, Jane. That name will always remind me of her.",
    "Vincent Ludwig [offering cigar]: Cuban? Frank: No, Dutch Irish. My father was from Wales.",
    "...... Bingo!",
    "I can sum that up for you in three words: Quentin Hapsburg.",
    "Rocco: Better hit the rack, McGirk. Frank: In a minute. First I want to make up a list of the people I’m gonna kill in the next couple of days. [writing a letter to Jane] My dearest schnooky-wookum dumpling buns, I miss you so much...",
    "Blowing away a fleeing suspect with my 44 Magnum used to mean everything to me. I enjoyed it... well who wouldn't?",
    "Sergeant, take her away and book her... Sergeant Takeraway. Sergeant Booker.",
    "Quentin Hapsburg: Drebin! Jane: Frank! Frank: You’re both right."
];
